### ISSUE TITLE
Page Previous / Page Next Focus gone when Pagination completed Prev/Next icons clicking with key 'Enter' 

### ISSUE THREAD

**Issue by lavarajallu** [carbon-design-system/ibm-cloud#116]
I am using import { EnhancedDataTable } from '@console/pal/Components' In this We have one Prop for pagination 
hidePagination={true}
In this pagination, PreviousPage/NextPage focus is lost. If the Pagination is completed at least the NextPage focus should move to PreviousPage. If the Previous Pagination is completed pagination should move to NextPage, But this is not happening.
This is Referral Link
https://pages.github.ibm.com/ibmcloud/pal/storybook/?path=/story/components-enhanceddatatable--table-with-title-and-description

**Comment by MaxHam** [comment]
Hi @lavarajallu , sorry for responding so late..
Please move this issue to the [ PAL repository.](https://github.ibm.com/ibmcloud/pal) 
This repository will not be maintained.
